### ISSUE TITLE
[Question] Possible collaboration for scene graph, layout logic

### ISSUE THREAD

**Issue by dmvaldman** [makepad/makepad.github.io#1]
Removing a lot of the rendering cruft in the browser is something I'm particularly interested in. Also having a direct API to GL from JavaScript, instead of string casting and the convoluted pipelines that exist on the web today.

I'm currently working on my own "layout" engine. It can be found [here](https://github.com/dmvaldman/samsara). It's mainly based on streams and FRP principles. It takes DOM events as input and it outputs CSS3 transforms, opacities and sizes (non-accelerated). That's all it does, and all it will ever do. It could be augmented to output to your GPU layer, while providing powerful scene graph, user input, primitives, a simple physics engine, and other things.

Some old examples can be [seen here](https://github.com/dmvaldman/samsara/tree/master/examples). They work on every modern device, but are designed for mobile devices.

Here's a newer example of a 3D scrollview (implemented in DOM): 
![helix_short](https://cloud.githubusercontent.com/assets/796394/16891382/d26bb4d2-4ac6-11e6-841f-76b437fb5626.gif)

**Comment by makepaddev** [comment]
Hi!, so i have my own layout engine idea which is very high performance and based on 'turtles'  its optimized to be very easy to understand and it'l be in there soon. I don't fully understand the power of your approach yet, but i'd be happy to talk about it.

**Comment by dmvaldman** [comment]
Looking forward to seeing it! Here's a somewhat long rant about my ideas regarding layout.

The architecture I've been playing with is one where the scene graph isn't described by a tree, at least not in the usual sense (one that is recursively walked). The scene graph is instead thought of as a stream data structure. That is, nodes in the tree emit `update` events when data changes, and child nodes subscribe to parent nodes. When a node updates, it composes its new layout information with its cached parent nodes layout, and then that is sent down the tree to its children. At the bottom of the tree is when things output to the DOM, or in your case, they'd output to your rendering layer. 

The nice part about this is that there is no need for dirty checking. The scene graph automatically updates all the things that need to change, and nothing more. All the dependencies between nodes are connected with passive event listeners. The other nice part is that the layout data in a node is also provided by a streaming data structure. So say the opacity of a node goes from 0 to 1, this transition is provided by a stream that then seamlessly merges into the stream of the scene graph. Updating raw data and updating the scene graph is all handled by the same thing.

Often when dealing with layout, you want to translate one node based on its size, or the size of another node. For example, when making a list, a `<div>` is translated by the width or height of its predecessor in the list. If the size of its predecessor changes, this translation needs to change. This kind of dependency management is easily encapsulated with streams. In the GIF above, everything is `{position: absolute}` in CSS, and all the layout is done manually. When one node's size changes, all the nodes further along in the helix shifts accordingly because of these passive listeners. You can see a simpler example [here](http://codepen.io/samsaraJS/pen/EVdvOJ).

The ultimate goal is an architecture where as the data changes, everything that depends on the data updates and gets spit out to the screen. Notice this is not the same as 

```
// view is function of input
view = function render(input)
```

because the render function is a black box, and coarse-grains the dependencies of input to output. If some small bit of data changes, the render function would need to be recomputed, and not just the parts that depend on the data. React makes a compromise by creating a diff/patch step. But really, no compromise is needed if you just avoid the entire paradigm of render functions.

There are no `render` functions in Excel, for instance. There are just listeners, and every time you create a dependency between two boxes, listeners are set up that create a causal connection. 

It is a bit much to a have a listener for everything that can possibly change in a document. But I think that if all you're concerned with is presentational (size, transforms and opacity), and not content-related, then it isn't a bad idea.

**Comment by makepaddev** [comment]
Ok so, in makepad the layoutflow will be executed in-line with the re-draw flow (the recreation of the commandbuffers), and can handle thousands of items in milliseconds im not sure how this would work with function based listener systems. In regenerating the buffers i also allow tweens to be happening in the GPU thread(main thread) so layouts can tween for free without any JS structures needed. Ill finish that first and then we can see.

**Comment by makepaddev** [comment]
Also i have automatic listeners on views as you use its properties in the 'compose' (i renamed react render to compose for the graphics nerds around) function which will facilitate the incremental regeneration as partial data changes, its like a render function that has automatic partial evaluation.. or thats the idea anyway, have to see if it really holds up.

**Comment by makepaddev** [comment]
The scenegraph in makepad is 'hybrid' its a combination of a scenegraph of views with a matrix stack and each view is a canvas with a 'todo' in which you can draw any number of layed-out-and-interactive lightweight widgets which can only be regenerated in one cycle when they need to change structurally

**Comment by dmvaldman** [comment]
Okay so some questions:

- Will there be a way of mixing in DOM content with WebGL content
- It there one `canvas` element everything is drawn to, or several (one per view?)

**Comment by makepaddev** [comment]
So no i wont support mixing DOM content with webGL content.
Also per worker tree in makepad there will be one canvas. You can have multiple canvasses on one page but they will start up independent workers as their execution backing.

**Comment by makepaddev** [comment]
Makepad is going to be a livecoding editor webapp/site. This repo is just to support that effort.
