### ISSUE TITLE
[Improvement] "find" feature for the editor

### ISSUE THREAD

**Issue by ErreMalote** [makepad/makepad.github.io#5]
when I press Ctrl + F to find text in the editor I cant find what I am looking for. I know it is in the canvas so it will be hard to implement.

**Comment by makepaddev** [comment]
Hi, yea its not hard to implement its just that i'm not working on UI bits for a while. Doing audio API and new low level render API. After that i will continue with find/replace and things like that. But thanks for noticing :)
