### ISSUE TITLE
How to apply alpha to background 

### ISSUE THREAD

**Issue by d4tocchini** [makepad/makepad.github.io#7]
I'm attempting to apply makepad output atop something like an a-frame scene, but I can't get any alpha through the canvas. Setting alpha:true on the canvas opt & an initial gl.clear doesnt seem to help for any the examples or anything I can contrive.  

There is clearly deep ideas in here, @makepaddev any pointers?

**Comment by makepaddev** [comment]
Makepad is simply using a webGL canvas, no more no less, so the options to the webGL canvas should work tbh, i'm currently rewriting the entire renderstack so it will be easier to poke around in it (its a bit convoluted atm)

**Comment by makepaddev** [comment]
All drawcommands are interpreted so you'd have to poke into the drawcommandstreams to figure out where the alpha ends up coming from

**Comment by makepaddev** [comment]
The idea of this renderer rewrite is also that webVR / 3D will become easily accessible for makepad architecture, so composing it like this will become much less of a need.

**Comment by d4tocchini** [comment]
ah, i see, my code was hitting the right conditional in `painterTodo`

**Comment by d4tocchini** [comment]
good to hear! i'm definitely picking up what you're putting down here. 

any luck with webvr / threejs integration?

how do you feel about things like a-frame / how do you see makepad fitting in to the 3d space?
